config/routes.rb
ActiveRecordRules::Engine.routes.draw do
  get "/", to: "rules#index", as: "index"
  get "/:id", to: "rules#show", as: "rule"
  post "/:id", to: "rules#trigger", as: "trigger"
  get "/:rule_id/:match_id", to: "rules#show_match", as: "rule_rule_match"
end

app/models/active_record_rules/application_record.rb
module ActiveRecordRules
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/active_record_rules/application_controller.rb
module ActiveRecordRules
  class ApplicationController < ActionController::Base
  end
end

app/controllers/active_record_rules/rules_controller.rb
module ActiveRecordRules
  class RulesController < ApplicationController
    include ActionView::Helpers::TagHelper

    cattr_accessor :format_record_proc, default: ->(record) { record.id.inspect }

    def index
      @model_name = params["model_name"].presence
      @record_id = params["record_id"].presence

      @models = ActiveRecordRules.all_rules.map do |rule|
        rule.referenced_classes.map(&:name)
      end.reduce(Set.new, &:+).sort

      @rules_and_matches = ActiveRecordRules.all_rules.map do |rule|
        klass = rule.referenced_classes.find { _1.name == @model_name }
        if @model_name && !klass
          nil # The rule doesn't mention the selected class, so don't show it
        elsif @model_name && @record_id
          if (record = klass.find_by(id: @record_id))
            [ rule, rule.rule_matches_for(record).size ]
          else
            [ rule, 0 ]
          end
        else
          [ rule, rule.rule_matches.size ]
        end
      end.compact
    end

    def show
      @model_name = params["model_name"].presence
      @record_id = params["record_id"].presence
      @page = params["page"].to_i

      @rule = ActiveRecordRules.find_rule(params["id"].to_i)
      render "not-found" unless @rule

      @models = @rule.referenced_classes.map(&:name).sort
      klass = @rule.referenced_classes.find { _1.name == @model_name }

      @record = klass.find_by(id: @record_id) if @model_name && @record_id
      if @record_id
        matches = @rule.rule_matches_for(@record)
      else
        matches = @rule.rule_matches
      end

      page_size = 20
      @max_page = (matches.size / page_size.to_f).ceil - 1
      @id_objects = matches
                    .drop(@page.to_i * page_size)
                    .take(page_size)
                    .map do |rule_match|
        [ rule_match,
         @rule.id_names_and_types.to_h do |name, type|
           [ name, type.find_by(id: rule_match.ids[name]) ]
         end ]
      end
    end

    def trigger
      @rule = ActiveRecordRules.find_rule(params["id"].to_i)
      render "not-found" unless @rule

      @model_name = params["model_name"].presence
      @record_id = params["record_id"].presence
      klass = @rule.referenced_classes.find { _1.name == @model_name }
      @record = klass.find_by(id: @record_id) if @model_name && @record_id

      pending_activations = if @record
                              @rule.calculate_required_activations(@record.class, nil, @record.attributes)
      end
      ActiveRecordRules.run_pending_executions(@rule.activate(pending_activations))

      path = [ "model_name", "record_id", "page" ].index_with { params[_1] }
      redirect_to rule_path(path), status: 303
    end

    def show_match
      @model_name = params["model_name"].presence
      @record_id = params["record_id"].presence
      @page = params["page"].to_i

      @rule = ActiveRecordRules.find_rule(params["rule_id"].to_i)
      render "not-found" unless @rule

      @rule_match = @rule.rule_matches.find(params["match_id"].to_i)
      render "not-found" unless @rule_match

      id_paths = @rule.extract_id_variables

      @live_arguments = @rule_match.live_arguments
      @next_arguments = @rule_match.next_arguments

      @argument_keys = @live_arguments&.keys.to_a | @next_arguments&.keys.to_a
      if @live_arguments
        @live_objects = id_paths.reduce(@live_arguments) do |result, (path, klass)|
          replace_ids(result, path, klass)
        end.transform_values { format_value(_1) }
      end

      if @next_arguments
        @next_objects = id_paths.reduce(@next_arguments) do |result, (path, klass)|
          replace_ids(result, path, klass)
        end.transform_values { format_value(_1) }
      end
    end

    private

    def replace_ids(arguments, path, klass)
      case [ path, arguments ]
      in [[], id]
        klass.find_by(id: id) || id
      in [[:all, *rest], _]
        arguments.map { replace_ids(_1, rest, klass) }
      in [[key, *rest], Hash => arguments]
        if arguments.key?(key)
          { **arguments, key => replace_ids(arguments[key], rest, klass) }
        else
          arguments
        end
      in [[key, *rest], Array => arguments]
        [ *arguments[...key], replace_ids(arguments[key], rest, klass), *arguments[key+1..] ]
      end
    end

    def format_value(value)
      tags = PrettyPrint.format(
        # output: an array to store tags
        [],
        # maxwidth:
        120,
        # newline:
        tag.br,
        # genspace:
        ->(n) { " " * n }
      ) { format_one_value(value, _1) }

      # We start the reduction with a HTML-safe string, so the result
      # keeps track of its safety along the way.
      tags.reduce("".html_safe, &:+)
    end

    def format_one_value(value, printer)
      case value
      in Array
        if value.empty?
          printer.text("[]", 2)
        else
          printer.text("[ ")
          printer.group(2) do
            value.each_with_index do |item, i|
              if i > 0
                printer.text(",")
                printer.breakable
              end
              format_one_value(item, printer)
            end
          end
          printer.text(" ]")
        end
      in ActiveRecord::Base
        string = format_record(value)
        printer.text(
          begin
            tag.a(string, href: main_app.url_for(value))
          rescue => e
            string
          end,
          string.length
        )
      else
        printer.text(value.inspect)
      end
    end

    helper_method :format_record

    def format_record(record)
      instance_exec(record, &self.class.format_record_proc)
    end
  end
end

app/helpers/active_record_rules/application_helper.rb
module ActiveRecordRules
  module ApplicationHelper
  end
end

app/views/active_record_rules/rules/index.html.erb
<h1>Rules</h1>
<%= form_with method: :get, html: { role: 'group' } do |form| %>
    <%= form.select :model_name, @models, include_blank: "Select a model", selected: @model_name %>
    <%= form.text_field :record_id, value: @record_id, placeholder: "Enter an id" %>
    <%= form.submit "Find matches" %>
<% end %>
<% @rules_and_matches.each do |rule, match_count| %>
    <article class="rule">
        <header>
            <a class="rule-link"
               href="<%= url_for controller: 'rules', action: 'show', id: rule.id, model_name: @model_name, record_id: @record_id %>"
               role="group">
                <h2 title="<%= rule.name %>"><%= rule.name %></h2>
                <div class="timing timing_<%= rule.timing %>"><%= rule.timing.to_s.gsub('_', ' ') %></div>
            </a>
        </header>
        <details>
            <summary role="button" class="secondary">Show definition (<%= rule.source_location.delete_prefix("#{Rails.root}/") %>)</summary>
            <pre><%= rule.constraints_string %></pre>
        </details>
        <footer>
            <a class="rule-link" href="<%= url_for controller: 'rules', action: 'show', id: rule.id, model_name: @model_name, record_id: @record_id %>">
                <% if match_count == 1 %>
                    <%= match_count %> match
                <% else %>
                    <%= match_count %> matches
                <% end %>
            </a>
        </footer>
    </article>
<% end %>

app/views/active_record_rules/rules/show.html.erb
<nav>
    <h1><%= link_to '⇐ Back to rules', index_path(model_name: @model_name, record_id: @record_id) %></h1>
</nav>

<%= form_with method: :get, html: { role: 'group' } do |form| %>
    <%= form.select :model_name, @models, include_blank: "Select a model", selected: @model_name %>
    <%= form.text_field :record_id, value: @record_id, placeholder: "Enter an id" %>
    <%= form.submit "Find matches" %>
<% end %>

<article class="rule">
    <header role="group">
        <h2><%= @rule.name %></h2>
        <div class="timing timing_<%= @rule.timing %>"><%= @rule.timing.to_s.gsub('_', ' ') %></div>
    </header>
    <details>
        <summary role="button" class="secondary">Show definition (<%= @rule.source_location.delete_prefix("#{Rails.root}/") %>)</summary>
        <pre><%= @rule.constraints_string %></pre>
    </details>
    <footer>
        <%= form_with do |form| %>
            <%= form.hidden_field :model_name, value: @model_name  %>
            <%= form.hidden_field :record_id, value: @record_id  %>
            <%= form.hidden_field :page, value: @page  %>
            <button>
                Trigger rule for <%= @record ? "#{@model_name} #{format_record(@record)}" : "all records" %>
            </button>
        <% end %>
    </footer>
</article>

<h2>Matches</h2>
<% @id_objects.each do |match, row| %>
    <a class="rule-link" href="<%= rule_rule_match_path(@rule.id, match.id, page: @page, model_name: @model_name, record_id: @record_id)  %>">
        <article>
            <dl>
                <% row.each do |name, record| %>
                    <dt><%= name %></dt>
                    <dd><%= format_record(record) %></dd>
                <% end %>
            </dl>
        </article>
    </a>
<% end %>

<% if @page > 0 %>
    <%= link_to '⇐ Prev', rule_path(page: @page - 1, model_name: @model_name, record_id: @record_id) %>
<% end %>
<% if @page < @max_page %>
    <%= link_to 'Next ⇒', rule_path(page: @page + 1, model_name: @model_name, record_id: @record_id) %>
<% end %>

app/views/active_record_rules/rules/show_match.html.erb
<nav>
    <h1><%= link_to '⇐ Back to rule matches', rule_path(@rule, page: @page, model_name: @model_name, record_id: @record_id) %></h1>
</nav>

<article class="rule">
    <header role="group">
        <h2><%= @rule.name %></h2>
        <div class="timing timing_<%= @rule.timing %>"><%= @rule.timing.to_s.gsub('_', ' ') %></div>
    </header>
    <details>
        <summary role="button" class="secondary">Show definition (<%= @rule.source_location.delete_prefix("#{Rails.root}/") %>)</summary>
        <pre><%= @rule.constraints_string %></pre>
    </details>
</article>


<article class="rule-match">
    <header>
        <h2>Rule matches</h2>
    </header>
    <dl>
        <% @argument_keys.each do |key| %>
            <dt><%= key %></dt>
            <dd>
                <pre><%= @live_objects[key] %></pre>
                <% if @next_objects && @next_objects[key] != @live_objects[key] %>
                    awaiting execution with next value:
                    <pre><%= @next_objects[key] %></pre>
                <% end %>
            </dd>
        <% end %>
    </dl>
</article>

app/views/layouts/active_record_rules/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Active record rules</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= yield :head %>

        <%= stylesheet_link_tag "active_record_rules/pico.min", media: "all" %>
        <%= stylesheet_link_tag "active_record_rules/application", media: "all" %>
    </head>
    <body>
        <main class="container">
            <%= yield %>
        </main>
    </body>
</html>